apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: alfred-ingress
  namespace: development-nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: dev.alfred
      http:
        paths:
        - path: /api/alfred/(.*)
          backend:
            serviceName: alfred-api
            servicePort: 8082
        - path: /*
          backend:
            serviceName: alfred-frontend
            servicePort: 8081
