apiVersion: v1
kind: Service
metadata:
  labels:
    testLabel: testValue
  name: alfred-api
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: https
    nodePort: 31433
    port: 443
    protocol: TCP
    targetPort: 80
  - name: http
    nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    Octopus.Kubernetes.DeploymentName: alfred
  sessionAffinity: None
  type: NodePort

