apiVersion: extensions/v1
kind: Deployment
metadata:
  labels:
    testLabel: testValue
  name: alfred
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      Octopus.Kubernetes.DeploymentName: alfred  
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  alfred-api
    spec:
      containers:
      - image:  ipedrazas/docmock
        name:  alfred-api

        livenessProbe:
          httpGet:
            path: /api/health/live
            port: 80
          initialDelaySeconds: 10
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/ready
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: urls__search
          value: http://p2-ci-web1.abcam.com    
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
      restartPolicy: Always
      imagePullPolicy: Always